# -*- coding: utf-8 -*-
"""RAG Based Q & A System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dNKODEcVGHJprqD9J-RuNyfMn4NDvrHv
"""

from google.colab import files

uploaded = files.upload()

import json

file_path = "6891f2d5155fc19d1c7a728a_output (2).jsonl"

with open(file_path, "r", encoding="utf-8") as f:
    for i, line in enumerate(f):
        print(json.loads(line))
        if i == 2:
            break

import json

records = []

file_path = "6891f2d5155fc19d1c7a728a_output (2).jsonl"

with open(file_path, "r", encoding="utf-8") as f:
    for line in f:
        records.append(json.loads(line))

print("Total records:", len(records))

"""# Convert JSON to RAG Documents"""

from langchain_core.documents import Document

documents = []

for record in records:

    messages = record["messages"]

    question = ""
    answer = ""

    for msg in messages:

        if msg["role"] == "user":
            question = msg["content"]

        elif msg["role"] == "assistant":
            answer = msg["content"]

    text = f"""
    Question: {question}

    Answer: {answer}
    """

    documents.append(
        Document(
            page_content=text,
            metadata={
                "question": question
            }
        )
    )

print("Documents:", len(documents))

"""# Build Embeddings"""

from langchain_community.embeddings import HuggingFaceEmbeddings

embeddings = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

"""# Create Chroma DB"""

from langchain_chroma import Chroma

vectordb = Chroma.from_documents(
    documents=documents,
    embedding=embeddings,
    persist_directory="./company_policy_db"
)

print("Vector DB created")

"""# Create Retriever"""

retriever = vectordb.as_retriever(search_kwargs={"k": 3})

"""# Load a LLM"""

from transformers import pipeline

llm = pipeline(
    "text-generation",
    model="TinyLlama/TinyLlama-1.1B-Chat-v1.0"
)

"""# Build Q&A function"""

def ask_question(query):

    docs = retriever.invoke(query)

    if not docs:
        return "No relevant answer found."

    context = "\n\n".join([d.page_content for d in docs])

    prompt = f"""
    Answer using only the context.

    Context:
    {context}

    Question:
    {query}

    Answer:
    """

    result = llm(prompt, max_new_tokens=150)

    return result[0]["generated_text"]

print(
    ask_question("Why is company policy reviewed every year?")
)